### ISSUE TITLE
ConfigurationProfilePresetCodes.isKnownPreset is not working

### ISSUE THREAD

**Issue by ivankhoosty** [aws/aws-advanced-jdbc-wrapper#1000]
### Describe the bug

static {
    registerProperties(**String**.class);
  }

should be 

static {
    registerProperties(ConfigurationProfilePresetCodes.class);
  }

so that the public static Strings get added to KNOWN_PRESETS

### Expected Behavior

known presets should be validated correctly

### What plugins are used? What other connection properties were set?

n/a

### Current Behavior

isKnownPreset method returns false for any value, as KNOWN_PRESETS is empty

### Reproduction Steps

ConfigurationProfilePresetCodes.isKnownPreset("D0") returns false

### Possible Solution

static {
    registerProperties(ConfigurationProfilePresetCodes.class);
  }

### The AWS Advanced JDBC Driver version used

2.3.6

### JDK version used

21.0.1

### Operating System and version

unix

**Comment by ivankhoosty** [comment]
https://github.com/aws/aws-advanced-jdbc-wrapper/blob/ed0082f31f65c7e8be560202e95bce937cd464a7/wrapper/src/main/java/software/amazon/jdbc/profile/ConfigurationProfilePresetCodes.java#L68

**Comment by sergiyvamz** [comment]
Hello @ivankhoosty 

Thanks for reaching out and raising this issue.

Fix https://github.com/aws/aws-advanced-jdbc-wrapper/pull/1004 is available on our latest snapshot build.
Could you check it out and let us know if the issue still persists?

Thank you!

**Comment by ivankhoosty** [comment]
thanks
