### ISSUE TITLE
Missing reference to aws-core as a dependency when deploying with the iam plugin to EKS

### ISSUE THREAD

**Issue by wawaberry** [aws/aws-advanced-jdbc-wrapper#1003]
### Describe the issue

After a successful execution of the aws-advanced-jdbc-wrapper locally, which uses DefaultCredentialsProvider we got the following snippet  in the stack trace after deploying to EKS -
```
Caused by: java.lang.NoClassDefFoundError: software/amazon/awssdk/awscore/AwsClient

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at software.amazon.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory$StsWebIdentityCredentialsProvider.<init>(StsWebIdentityCredentialsProviderFactory.java:70)
```

Turns out the generated interface StsClient is inherited from AwsClient in the awscore package.
Our solve was to include - 
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-core</artifactId>
            <version>2.25.53</version>
        </dependency>
        
 I only found artifacts rds and sts as dependencies in the documentation and on maven central.   

### Links

https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md#prerequisites

**Comment by aaronchung-bitquill** [comment]
Hi @wawaberry,

Thank you for reaching out and raising this with us. 

We'll be taking a look at this and keep you updated. 

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @wawaberry 

I wanted to let you know that changes have been merged to make the dependency requirements clearer in the documentation, as well as to check in and see if you had any other questions or concerns? If there are no updates on this ticket in the next few days, it will be closed. However, if there is anything else, please feel free to reopen this issue or to create a new one.

Thank you!

**Comment by wawaberry** [comment]
@aaronchung-bitquill  Thank you,  The documentation update is helpful.
