### ISSUE TITLE
Links to profiles and configuration sets are broken in the examples readme's

### ISSUE THREAD

**Issue by krisiye** [aws/aws-advanced-jdbc-wrapper#1017]
### Describe the issue

Links to Configuration Profiles and Configuration Presets under the following examples are broken:
SpringHibernateBalancedReaderTwoDataSourceExample
SpringHibernateBalancedReaderOneDataSourceExample

### Links

https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/examples/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#configuration-profiles
https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/examples/docs/using-the-jdbc-driver/ConfigurationPresets.md
https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/examples/docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md

**Comment by aaronchung-bitquill** [comment]
Hi @krisiye 

Thanks for raising this issue and making a pull request fix for it! 

I'll take a look at your pull request and try to get it merged in soon. 

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @krisiye 

Just merged in your fix. Thank you for your contribution!

**Comment by krisiye** [comment]
> Hi @krisiye
> 
> Just merged in your fix. Thank you for your contribution!

Thanks for the review and merge! I did some testing and it works for the most part except for the auto scroll for configuration-profiles. Maybe this is a github .md limitation.

**Comment by aaronchung-bitquill** [comment]
Yeah. I think its a Github bug. When navigating to an anchored link via .md file, it doesnt scroll down to the anchored section. But if I visit the link (with the anchor in the URL) directly, it auto scrolls properly.

**Comment by krisiye** [comment]
Reported https://github.com/github/markup/issues/1807
