### ISSUE TITLE
According to the List of Available Plugins, the IAM Authentication Connection Plugin is not compatible with Plain RDS

### ISSUE THREAD

**Issue by dzagorovsky** [aws/aws-advanced-jdbc-wrapper#1034]
### Describe the issue

According to the [List of Available Plugins table](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#list-of-available-plugins) the [IAM Authentication Connection Plugin](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md) is compatible with Aurora only (Database Compatibility column).
<img width="899" alt="image" src="https://github.com/aws/aws-advanced-jdbc-wrapper/assets/6490311/3cd95ff9-9b4f-4ad8-a813-48e80153c372">

However, the plain RDS documentation article [IAM database authentication for MariaDB, MySQL, and PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) refers to the [AWS IAM Authentication Plugin](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md) in context of the [AWS JDBC driver wrapper](https://github.com/aws/aws-advanced-jdbc-wrapper).

As far as I understand, the [IAM Authentication Connection Plugin](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md) is compatible with `Any database` and this should be stated in the [List of Available Plugins table](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#list-of-available-plugins) instead of `Aurora`.

### Links

https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#list-of-available-plugins

`Database Compatibility` column should contain `Any database` instead of `Aurora` in `IAM Authentication Connection Plugin` row.

**Comment by hsuamz** [comment]
Thanks for reaching out @dzagorovsky and raising this issue.

You are correct, our documentation on GitHub was outdated. The following PR (#1044) was recently merged in which addresses the issue.

We'll be closing this issue. Please reach out again if you have any questions.

Thanks again!
