### ISSUE TITLE
failover2 plugin only looks at wrapperPlugins and ignores pluginFactories

### ISSUE THREAD

**Issue by ivankhoosty** [aws/aws-advanced-jdbc-wrapper#1140]
### Describe the bug

thank you for failover2 plugin, i think it will address https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1026

I use pluginFactories to specify plugins, not wrapperPlugins property string.

When I tried to upgrade to 2.4.0, I came across an issue at https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java?secureweb=Teams#L133

Because of https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginChainBuilder.java?secureweb=Teams#L145 , where preference is given to pluginFactories , it's possible to have a workaround and specify 

targetDataSourceProperties.setProperty(PropertyDefinition.PLUGINS.name, "failover2");

and get passed this issue.

### Expected Behavior

code in AuroraPgDialect should take pluginFactories into account

### What plugins are used? What other connection properties were set?

failover2

### Current Behavior

wrapperPlugins need to contain "failover2" for AuroraPgDialect to use MonitoringRdsHostListProvider

### Reproduction Steps

use failover2 plugin with pluginFactories only

### The AWS Advanced JDBC Driver version used

2.4.0

### JDK version used

21

### Operating System and version

unix

**Comment by sergiyvamz** [comment]
Hi @ivankhoosty ,

Could you please verify if the latest changes address the issue for you? You can find the latest change in the snapshot build. More information on how to use the snapshot build is available [here](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver).

Thank you!

**Comment by ivankhoosty** [comment]
Hi @sergiyvamz , unfortunately it's prob easier to rob a bank than to onboard a snapshot - about 4 weeks process etc :(

I can confirm that 2.4.0 is working great with failover2 plugin and  the two workarounds (above, and clusterId), and i am going to close https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1026
