### ISSUE TITLE
ConfigurationProfileBuilder withAwsCredentialsProviderHandler is not working

### ISSUE THREAD

**Issue by ivankhoosty** [aws/aws-advanced-jdbc-wrapper#1181]
### Describe the bug

I wanted to set an (existing) awsCredentialsProvider bean for the driver to use, rather than fallback to DefaultCredentialsProvider, and it didn't work. Looking at the code, ConfigurationProfileBuilder withAwsCredentialsProviderHandler never calls AwsCredentialsManager.setCustomHandler to actually use the provided AwsCredentialsProviderHandler.

### Expected Behavior

ConfigurationProfileBuilder withAwsCredentialsProviderHandler should make sure that AwsCredentialsProviderHandler with awsCredentialsProvider is used by the driver in aws sdk calls.

### What plugins are used? What other connection properties were set?

ConnectTimeConnectionPluginFactory, ExecutionTimeConnectionPluginFactory, AuroraInitialConnectionStrategyPluginFactory, AuroraConnectionTrackerPluginFactory, FailoverConnectionPluginFactory, IamAuthConnectionPluginFactory

### Current Behavior

 ConfigurationProfileBuilder.get().withAwsCredentialsProviderHandler((hostSpec, props) -> awsCredentialsProvider) isn't doing anything, so it's necessary to call: AwsCredentialsManager.setCustomHandler((hostSpec, props) -> awsCredentialsProvider);

### Reproduction Steps

ConfigurationProfileBuilder.get().withAwsCredentialsProviderHandler((hostSpec, props) -> awsCredentialsProvider)

then observe that this awsCredentialsProvider is never used in aws sdk calls.

### The AWS Advanced JDBC Driver version used

2.5.2

### JDK version used

21.0.1

### Operating System and version

unix

**Comment by aaron-congo** [comment]
Hi @ivankhoosty ,

We have just merged in a fix. Could you kindly checkout our latest [snapshot](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by aaron-congo** [comment]
Hi @ivankhoosty,

The fix is now available in the recently released v2.5.3 of the driver. Since the fix is now released I will be closing this ticket. Please feel free to re-open or create a new ticket if you encounter any issues.

Thank you!

**Comment by ivankhoosty** [comment]
Hi @aaron-congo , sorry I couldn't test the snapshot, but just got 2.5.3 and the bug is fixed. many thanks
