### ISSUE TITLE
Incorrect port for MySQL example

### ISSUE THREAD

**Issue by davecramer** [aws/aws-advanced-jdbc-wrapper#1220]
https://github.com/aws/aws-advanced-jdbc-wrapper/blob/efc2df46d1d3440cb3e95638483576e485e7cf37/examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingMySQLExample.java#L37C81-L37C85

Please change port to 3306

**Comment by aaron-congo** [comment]
Fixed in https://github.com/aws/aws-advanced-jdbc-wrapper/pull/1224
