### ISSUE TITLE
Option to specify priority/weight in HostSpec

### ISSUE THREAD

**Issue by Sovietaced** [aws/aws-advanced-jdbc-wrapper#231]
### Describe the feature

I'm currently working on a `HostListProvider` that does topology discovery using AWS APIs to support Aurora Global Database. I'm trying to make it such that DB connections will be made to local regions when possible. 

When reader failover occurs the available reader hosts are shuffled and connected to at random. I think this is a good strategy for distributing connections among a local cluster with many readers but less optimal in a global database where reads to a distant region can add significant latency to DB queries. 

### Use Case

I'm currently working on a `HostListProvider` that does topology discovery using AWS APIs to support Aurora Global Database. I'm trying to make it such that DB connections will be made to local regions when possible. I need a way to weigh/prioritize `HostSpec` objects such that clients will failover to local readers as opposed to remote readers. 

### Proposed Solution

I propose the option to specify an optional (default to 0) priority/weight to each `HostSpec` object such that certain hosts will be higher priority than others. Then the reader failover behavior could be updated to group hosts by priority and shuffle at each priority. For the `AuroraHostListProvider` there would be no behavior change. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

JDK 11

### Operating System and version

Ubuntu 20.04

**Comment by davecramer** [comment]
Interesting. What is the basis for favouring one host over another ?

**Comment by Sovietaced** [comment]
> Interesting. What is the basis for favouring one host over another ?

Let's say I have an Aurora global DB in two regions, us-east-1 and us-west-2. The purpose of the Aurora global DB is for disaster recovery purposes. My applications run in us-east-1 so it would be ideal for my database connections to be made to a reader in us-east-1 so that I don't incur unnecessary latency making requests to us-west-2.

**Comment by kitsirota** [comment]
+1 Specifying the region to use for global database requests is critical to high-throughput, low-latency workloads.

**Comment by davecramer** [comment]
@kitsirota thanks for the feedback

**Comment by aaron-congo** [comment]
Hi @Sovietaced, I'm in the process of going through our open issues right now and it seems we forgot to follow up on this - my apologies. The `weight` property was added to the HostSpec class in version 2.0.0. I will be closing this ticket because this is already added, however, if you require further assistance, you can reopen this issue, or create a new one. Thanks!
