### ISSUE TITLE
XA not supported

### ISSUE THREAD

**Issue by mwgreen** [aws/aws-advanced-jdbc-wrapper#639]
### Describe the issue

According to this closed issue:

https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/511

XA datasources are not supported.

It would be very nice to support XA Datasources, however 2 things:

The docs say "drop in replacement". This makes that not-true
This is not in the 'known limitations' document

This is very much needed, BTW

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/511

https://awslabs.github.io/aws-postgresql-jdbc/

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/KnownLimitations.md

**Comment by davecramer** [comment]
Hi @mwgreen 

I'm curious what your expectation would be here. In the event of a failover any 2 phase commit will certainly fail. How should the driver deal with this in your view ?

Dave

**Comment by mbialozor** [comment]
Any update on this topic, Guys?

**Comment by flauschie** [comment]
@davecramer 

It is understood that in case of a failover, the commit fails. 

But the issue is that you can't even configure the XADatasource of the underlying driver, as I mentioned in https://github.com/aws/aws-advanced-jdbc-wrapper/issues/511

So, even during normal operation, XA isn't possible.

**Comment by davecramer** [comment]
Any future work will be done in https://github.com/aws/aws-advanced-jdbc-wrapper please open this issue there

**Comment by flauschie** [comment]
Why was this issue closed? The last comment doesn't make any sense - this is the track for the JDBC wrapper.

**Comment by s4a-mjarosz** [comment]
@finlaycurran, you ca track the progress also in https://github.com/aws/aws-advanced-jdbc-wrapper/issues/511.

But, I agree, that "closed this as **completed**" is not really true.

**Comment by finlaycurran** [comment]
@s4a-mjarosz I think you tagged the wrong person! 

@flauschie see above

**Comment by davecramer** [comment]
> @davecramer
> 
> Why was this issue closed? The last comment doesn't make any sense - this IS the tracker ticket for the JDBC wrapper.

You are correct, my apologies
