### ISSUE TITLE
Improve logging levels

### ISSUE THREAD

**Issue by lujop** [aws/aws-advanced-jdbc-wrapper#890]
### Describe the feature

Currently, if we want to get logs when the plugin reacts to a failover, we need to set level to FINE and the log gets noisy from other not-so-important information

### Use Case

When using failover,efm plugins, and enabling FINE to have some information when the driver reacts to a failover, we end up having noisy messages:
[Releasing resources](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/96ac0d8d2a0286abbd834691f4df71bce27b7892/wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java#L530)

### Proposed Solution

Could the Releasing resources be logged using another finer category or even better promote to info the `Failover.startWriterFailover` and `Failover.establishedConnection`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

Latest

### JDK version used

11

### Operating System and version

MAC OS X

**Comment by jasonlamz** [comment]
Hi @lujop,

Could you please tell me if you are using a `.properties` file?

If not, could you please try [enabling logging](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging) using a `logging.properties` file?
Here is a sample logging.properties file:

```
.level=INFO
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=ALL
software.amazon.jdbc.Driver.level=FINE
software.amazon.jdbc.plugin.level=FINE
software.amazon.jdbc.PluginServiceImpl.level=FINER
```

This should allow you to choose the logging level per package. Please let me know if you have any questions or concerns.

Thank you!

**Comment by lujop** [comment]
Thanks, @jasonlamz; I already know how to configure the loggers per category.
However, one problem is that we use SLF4J to unify several logger implementations. And up to my knowledge, it converts FINER and FINEST to TRACE, and we lose some detail here.
Also, I think that it will be nice to have some way to get some insights without being so noisy and without having to tune each class separately.

**Comment by jasonlamz** [comment]
Hi @lujop,

We have just merged in a PR for this. Could you kindly checkout our [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by hsuamz** [comment]
Closing this issue since we haven't seen a response. Please feel free to re-open this issue if the issue still persists.

Thanks!
