### ISSUE TITLE
Support another language Dotnet or Python

### ISSUE THREAD

**Issue by tieungao88** [aws/aws-advanced-jdbc-wrapper#899]
### Describe the feature

I want driver support another language

### Use Case

I have many project with Dotnet or Python.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.3.0

### JDK version used

17

### Operating System and version

amazonelinux

**Comment by hsuamz** [comment]
Hello @tieungao88,

Thanks for reaching out and bringing this topic up. For visibility, the team is currently looking at Python as another language for the driver to support. At this time, we cannot share exact timelines, but will make sure to update this issue when we have an update to share.

Thanks,

Matthew

**Comment by hsuamz** [comment]
Hello @tieungao88,

Following up regarding this, we have recently released a Python version of the driver. For more information, you can refer this [Blog Post](https://aws.amazon.com/blogs/database/introducing-the-advanced-python-wrapper-driver-for-amazon-aurora/). It will contain all the relevant links to get you started with the driver.

Thanks,

Matthew

**Comment by hsuamz** [comment]
Will be closing this issue. As new language drivers are released, we'll be making official announcements.

Regarding Dotnet, thank you for the feedback. We have relayed this information to our product team. To re-iterate, if you're interested in Python, please check the previous reply in this thread for the official release announcement.

Thank you!
