### ISSUE TITLE
Test with recent version of Aurora PostgreSQL (for example 15.5)

### ISSUE THREAD

**Issue by ahus1** [aws/aws-advanced-jdbc-wrapper#937]
### Describe the feature

Test and support a recent built of PostgreSQL, for example 15.5

### Use Case

In the project's readme at the very end, Aurora PostgreSQL 15.2 is mentioned, together with PostgreSQL 15.2. 
When I'm using Aurora PostgreSQL 15.5, I want to be sure the JDBC wrapper works fine with that release of of the wrapper.

### Proposed Solution

With 15.5 being supported with Aurora since December 2023, I would be glad if you could re-run your tests with that version. Jumping to 16.x wouldn't be essential for now. 

### Other Information

We're running our application's testsuite with the JDBC wrapper 2.3.1 against 15.5 without problems, so I'll keep my fingers crossed that your tests will work as well.
(We would upgrade to a more recent JDBC wrapper if it wouldn't be for #921, #917 and #893)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.3.1

### JDK version used

17

### Operating System and version

Linux

**Comment by ahus1** [comment]
I see in the logs that the current builds for "Run Aurora Integration Tests LTS" and "Run Aurora Integration Tests Latest" work with 15.4 and 16.1 when searching in the logs "Using aurora-postgresql". 

While some previous builds were green, the latest builds seems to be failing. Should I be worried?

**Comment by sergiyvamz** [comment]
Hi @ahus1 

There were some issues with triggering failover on Aurora test clusters. They have been resolved and all tests pass now.

https://github.com/awslabs/aws-advanced-jdbc-wrapper/actions/runs/8604896133
https://github.com/awslabs/aws-advanced-jdbc-wrapper/actions/runs/8604896122

**Comment by ahus1** [comment]
@sergiyvamz - thank you for the update, and congrats on the green builds. 

The [README](https://github.com/awslabs/aws-advanced-jdbc-wrapper?tab=readme-ov-file#aurora-engine-version-testing) still states PostgreSQL 15.2 as the tested version, still I see that the LTS builds use the main branch against 15.4, and the latest uses 16.1.

The question that remains for me: Which version of Aurora PostgreSQL is the supported and tested version 2.3.5 for the JDBC wrapper? I would be happy for an update of the README.

**Comment by aaron-congo** [comment]
Hi @ahus1, it appears we forgot to follow up here, my apologies. We currently test against the latest Aurora Postgres version and the default Aurora Postgres version. Both versions may change over time, but currently the latest is 16.3 and the default is 15.4. Note that the README mentions that we test against the latest version and the LTS version, but this is slightly inaccurate - instead of the LTS version, we test against the default one. I'll update the README to correct this.

Do you still need the tests to be run against 15.5 specifically? Or are the current tested versions fine for you (16.3 and 15.4)?

**Comment by aaron-congo** [comment]
Hi @ahus1, I wanted to check in and see if you saw my response above. Please let me know. If there are no further updates on this ticket in the next few days, we will close this ticket. However, if you require further assistance, you can reopen this issue, or create a new one.

Thank you!

**Comment by ahus1** [comment]
Sorry for the late reply - thank your for the update. This is sufficient for me.
