### ISSUE TITLE
RDSUtils does not support region us-isob-east-1

### ISSUE THREAD

**Issue by jameshcovington** [aws/aws-advanced-jdbc-wrapper#998]
### Describe the bug

This might be more far-reaching than simply RDSUtils.java, but here at least we are getting an exception when using the driver in regions like us-isob-east-1. The exception is raised when invoking getRdsRegion, and the problem is the Pattern AURORA_DNS_PATTERN is hardcoded to only recognize "rds.amazonaws.com" as the dns suffix, when this is not the case in the us-isob-east-1 region, where the DNS suffix is sc2s.sgov.gov.

### Expected Behavior

Expect valid RDS cluster endpoints in the us-isob-east-1 region are regarded as such.

### What plugins are used? What other connection properties were set?

N/A

### Current Behavior

Get "unsupported AWS host name" exception.

### Reproduction Steps

specify a jdbc connection string with an RDS endpoint from the specified region.

### Possible Solution

Add Pattern object for the specified region's DNS suffix

### The AWS Advanced JDBC Driver version used

Current

### JDK version used

1.8

### Operating System and version

RHEL 8

**Comment by jameshcovington** [comment]
Am testing a fix that includes the following additions/changes to RdsUtils.java:
```java

  private static final Pattern AURORA_SC2S_DNS_PATTERN =
      Pattern.compile(
          "(?<instance>.+)\\."
              + "(?<dns>proxy-|cluster-|cluster-ro-|cluster-custom-)?"
              + "(?<domain>[a-zA-Z0-9]+\\.(?<region>[a-zA-Z0-9\\-]+)\\.rds\\.sc2s\\.sgov\\.gov)",
          Pattern.CASE_INSENSITIVE);

  private static final Pattern AURORA_SC2S_CLUSTER_PATTERN =
      Pattern.compile(
          "(?<instance>.+)\\."
              + "(?<dns>cluster-|cluster-ro-)+"
              + "(?<domain>[a-zA-Z0-9]+\\.(?<region>[a-zA-Z0-9\\-]+)\\.rds\\.sc2s\\.sgov\\.gov)",
          Pattern.CASE_INSENSITIVE);

```

then modifying these calls that reference existing Pattern objects:
```java
  public boolean isRdsDns(final String host) {
    final Matcher matcher = cacheMatcher(host, AURORA_DNS_PATTERN, AURORA_CHINA_DNS_PATTERN, AURORA_SC2S_DNS_PATTERN);
    final String group = getRegexGroup(matcher, DNS_GROUP);
    if (group != null) {
      cachedDnsPatterns.put(host, group);
    }

    return matcher != null;
  }

  public @Nullable String getRdsInstanceId(final String host) {
    if (StringUtils.isNullOrEmpty(host)) {
      return null;
    }

    final Matcher matcher = cacheMatcher(host, AURORA_DNS_PATTERN, AURORA_CHINA_DNS_PATTERN, AURORA_SC2S_DNS_PATTERN);
    if (getRegexGroup(matcher, DNS_GROUP) == null) {
      return getRegexGroup(matcher, INSTANCE_GROUP);
    }

    return null;
  }

  public String getRdsInstanceHostPattern(final String host) {
    if (StringUtils.isNullOrEmpty(host)) {
      return "?";
    }

    final Matcher matcher = cacheMatcher(host, AURORA_DNS_PATTERN, AURORA_CHINA_DNS_PATTERN, AURORA_SC2S_DNS_PATTERN);
    final String group = getRegexGroup(matcher, DOMAIN_GROUP);
    return group == null ? "?" : "?." + group;
  }

  public String getRdsRegion(final String host) {
    if (StringUtils.isNullOrEmpty(host)) {
      return null;
    }

    final Matcher matcher = cacheMatcher(host, AURORA_DNS_PATTERN, AURORA_CHINA_DNS_PATTERN, AURORA_SC2S_DNS_PATTERN);
    final String group = getRegexGroup(matcher, REGION_GROUP);
    if (group != null) {
      // Using replaceAll to strip 'rds' in case it is a China endpoint.
      return group.replaceAll("rds", "").replaceAll("\\.", "");
    }

    final Matcher elbMatcher = ELB_PATTERN.matcher(host);
    if (elbMatcher.find()) {
      return getRegexGroup(elbMatcher, REGION_GROUP);
    }
    return null;
  }

  public String getRdsClusterHostUrl(final String host) {
    if (StringUtils.isNullOrEmpty(host)) {
      return null;
    }

    final Matcher matcher = AURORA_CLUSTER_PATTERN.matcher(host);
    if (matcher.find()) {
      return host.replaceAll(AURORA_CLUSTER_PATTERN.pattern(), "${instance}.cluster-${domain}");
    }
    final Matcher chinaMatcher = AURORA_CHINA_CLUSTER_PATTERN.matcher(host);
    if (chinaMatcher.find()) {
      return host.replaceAll(AURORA_CHINA_CLUSTER_PATTERN.pattern(), "${instance}.cluster-${domain}");
    }
    final Matcher sc2sMatcher = AURORA_SC2S_CLUSTER_PATTERN.matcher(host);
    if (sc2sMatcher.find()) {
      return host.replaceAll(AURORA_SC2S_CLUSTER_PATTERN.pattern(), "${instance}.cluster-${domain}");
    }
    return null;
  }

```

**Comment by aaronchung-bitquill** [comment]
Hi @jameshcovington 

Thanks for reaching out raising this issue. 
Given that you are already working on a solution, would you like to open a pull request?

**Comment by jameshcovington** [comment]
Modified the above approach by simply modifying the existing Patterns. Pull request has been opened.

**Comment by aaronchung-bitquill** [comment]
Thank you @jameshcovington !

Will be taking a look at your pull request!

**Comment by aaronchung-bitquill** [comment]
Hi @jameshcovington 

Your fix has been approved and merged! Could you kindly checkout our [snapshot](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @jameshcovington ,

The fix is now available on the [latest version](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.7/jar) of the AWS Advanced JDBC Driver. 

Could you check it out let us know if the issue still persists?

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @jameshcovington ,

I wanted to check in.

If there are no further updates on this ticket in the next few days, we will close this ticket. However, if you require further assistance, you can reopen this issue, or create a new one.

Thank you!
